apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalyr-helm.fullname" . }}-config-agent-d
  labels:
  {{- include "scalyr-helm.labels" . | nindent 4 }}
data:
  {{- if .Values.supportK8s }}
  "kubernetes.json": |
    {
      "monitors":[
        {
          "module": "scalyr_agent.builtin_monitors.kubernetes_events_monitor"
        },
        {
          "module": "scalyr_agent.builtin_monitors.kubernetes_monitor"
        }
      ]
    }
  {{- end }}
  {{ with .Values.scalyr.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
